* Parameter choices
NX, NZ = number of points
LX, LZ = non-dimensional lengths

Smyth, Moum & Caldwell have dimensional values

h* = 1m - 25m = width of shear layer
u* = 0.5 - 2m/s = Δu across shear layer
t = h*/u*
B* = N² × h* = 1e-3 × 10 = 1e-3 ≡ 1 kg/m³ density jump across

sampling properties:
Z = 1-2m; U = 0.2-0.5m/s (this should be related to ΔU); T = 5-25s

CTD Δz = 10-20m
* Next steps [2/6]
1. [ ] What is the "true" value of heat flux to compare against?
   1. Need to compare inferred Jq against ΔBPE in /volume sampled by χpod/. Or something like that?
      - *This doesn't seem like a good way to do it.*
      - I can use ~bpe.Z~ (this goes from 0 to 25 but ~coords.z~ goes from -12.5 to 12.5)
      - Maybe there is something useful in the "localized" APE literature.

   2. Let's say that flux through a z-level is the flux through the _isosurface most often seen at that level_?
      - i.e. volume averaged wda flux in sampled-volume should converge to the OC estimate across that level and to cross-isosurface flux?
      - Another way to frame this: given a sampled volume and the true 3D buoyancy pdf, for which isosurface do our observations characterize the cross-isosurface flux in sorted space (i.e. the true value)? mean/median of observed buoyancy?

2. [X] Do non-dimensionalization more carefully [2/2]
   - [X] Could remove re-dimensionalization from ~sample_along_trajectory~
   - [X] Fix non-dimensionalization of ε, χ in ~process_sampled_field~ and other WDA stuff.

3. [X] Add some mooring gradient estimates

4. What is the "true" gradient? Smyth et al. (2001) over the shear layer?
   - [ ] ⟨χ⟩ / ∫φ dV
   - [ ] ⟨χ⟩ / <wb>?

5. [ ] Make cool movie

6. [ ] Compare sign of <w'b'> with dT/dz. This should tell me something about sign of heat flux?

7. [ ] Do localized APE budgets help?
